version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/comezc/project:/var/www/html/:rw
      - ./conf/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/:/var/log/dnmp/:rw
    networks:
      - net-php

  php71:
    build: ./php/php71/
    expose:
      - "9000"
    volumes:
      - /home/comezc/project:/var/www/html/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
    networks:
      - net-php
      - net-mysql
      - net-redis

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "laradock@root2018"

  redis:
    image: redis:4.0
    volumes:
    - ./conf/redis.conf:/usr/local/etc/redis/redis.conf:rw
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - net-redis
    ports:
      - "6379:6379"

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    ports:
#      - "8080:80"
#    networks:
#      - net-mysql
#    environment:
#      - PMA_HOST=mysql
#      - PMA_PORT=3306
#
#  phpredisadmin:
#    image: erikdubbelboer/phpredisadmin:latest
#    ports:
#      - "8081:80"
#    networks:
#      - net-redis
#    environment:
#      - REDIS_1_HOST=redis
#      - REDIS_1_PORT=6379

networks:
  net-php:
  net-mysql:
  net-redis:
